---
plugin: com.gatehill.imposter.plugin.rest.RestPluginImpl
contentType: application/json
resources:
  - path: "/cats/:id"
    type: array
    response:
      staticFile: cats.json
  - path: "/dogs/:id"
    type: array
    response:
      staticFile: dogs.json
